### ISSUE TITLE
Ekman Taxonomy  질문드립니다.

### ISSUE THREAD

**Issue by jaehong-k** [searle-j/KOTE#2]
안녕하세요! 훌륭한 데이터셋을 만들어주심에 정말 감사드립니다.
혹시, 해당 데이터셋을 Ekman Taxnomy로 grouping 하실 계획도 있으신지 궁금합니다. 한국 문장에서 뽑힌 감정과 외국의 감정에서 뽑힌 감정을 globally 비교할 때 큰 도움이 되리라 생각됩니다 :)

paper에서 언급해주신 GoEmotion 데이터 Ekman Taxnomy로 그루핑하는 과정이 있었어서, 혹시 개발자님도 Ekman Taxnomy를 고민해보셨을까하여 질문드립니다. 만들어주신 데이터로 grouping을 고민하고 있는데, 특별히 참고할만 자료를 찾지 못하여 여기에 글을 남기게 됐습니다ㅠㅠ

**Comment by searle-j** [comment]
안녕하세요.

현재로는 레이블 grouping에 관해 별다른 계획은 없습니다. 아쉽게도 연구 과정에서도 레이블을 grouping 해 본 적은 딱히 없습니다. paper에서 heatmap을 그릴 때 레이블의 순서가 유클리드 거리의 제곱으로 클러스터링한 결과를 따르도록 했는데, 그나마 grouping과 관련된 내용이라면 그게 전부입니다. 혹시 선생님의 연구에서 좋은 결과를 얻게 되시면 공유 부탁 드립니다 :)

**Comment by jaehong-k** [comment]
> 

친절히 답변해주심에 정말 정말 감사합니다 :)
말씀해주신부분(클러스터링 결과) 참고하여, Ekman Taxnomy를 한번 구성해보도록 하겠습니다! 구성하는대로, 이 곳에 답글 달아두도록 하겠습니다!
혹시, 클러스터링 결과 관련된 수치 자료도 혹시 남아 계실까요?! 계층군집화를 시행하거나 임계값을 정하여 grouping을 시행한다면 연구를 진행할때, 주관을 조금 덜 개입할 수 있을 것 같아서요!
현재는 논문에 있는 클러스터링 색상 값을 기준으로 각 대표 감정(Disgust, Fear, Sadness, No Emotion, Surprise, Joy)와의 거리를 계산하여 이렇게 나눠보았습니다! 해당 방식으로 에크만 Taxomony 데이터를 만들어보려고 합니다 :) 혹시 의견이나 피드백 있으시면 나눠주시면 감사하겠습니다 :)
- Disgust: fed up, shock, disgust, contempt
- Anger: anger, irritation, dissatisfaction,  preposterous
- Fear: pathetic, distrust, disappointment, embarrassment, shame, guilt, gessepany, fear, anxiety
- Sadness: compassion, sadness, sorrow, despair, exhaustion, laziness, reluctant, boredom
- No Emotion: no emotion arrogance, resolute
- Surprise: realization, surprise, respect, Interest 
- Joy: Expectancy, Welcome, Care, attracted, Excitement, joy, happiness, admiration, pride, gratitude, relief, comfort

기쁨 가득한 하루 되세요 :)

**Comment by jaehong-k** [comment]
안녕하세요 선생님. 조금 전에 Ekman Taxonomy 버전으로 데이터를 수정하여 허깅페이스에 업로드 해두었습니다:)
https://huggingface.co/datasets/kjhkjh95/kote_ekman
전처리를 한후, KcELECTRA로 fine-tune을 해보니 Macro F1기준 0.78이 나오네요 :)
내일중으로 허깅페이스에 모델을 업로드 해두고, 제 github 레퍼지토리에도 코드와 데이터를 업로드해두도록 하겠습니다 :)
좋은 데이터 만들어주심에 다시 한번 감사드립니다.
기쁨 가득한 하루되세요 :)

**Comment by ByungjunKim** [comment]
재홍 굿. 한번 테스트해보겠습니다.

**Comment by Esantomi** [comment]
@kjhkjh95 안녕하세요, 선생님.

김병준 선생님께 소개받고 댓글 남깁니다. 혹시 새로이 데이터셋 구축에 인력(?)이 필요하시면 연락을 부탁드립니다. 저는 한국학중앙연구원에서 디지털인문학을 공부하고 있습니다.

**Comment by jaehong-k** [comment]
@Esantomi 
아이고 ㅠㅠ 감사합니다 :) 사실, 저는 한 것이 거의 없고 이 git repository 주인분께서 해주신 것을, 그냥 Grouping 만하였습니다.
저는 카이스트 소셜컴퓨팅 연구실에서 공부하고 있습니다:)
데이터셋 구축 관련하여, 일이 생기거나 문의 사항이 생긴다면 선생님께 연락드리도록 하겠습니다.
참고로, 저는 자살예방에 관심이 많습니다. 혹시 관련 연구 인력(?)이 필요하다면 편하게 연락주세요. 
감사합니다 :)
기쁨 가득한 하루되세요!
